### ISSUE TITLE
Unable to compile in Typescript Node environment

### ISSUE THREAD

**Issue by Jackman3005** [ehmicky/modern-errors-serialize#2]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

I am unable to import this library into my codebase. I think it is because the published version is not compiled to module system I can use (?).

It's quite possible there is something on my side that is causing the issue, or some configuration I could change to get it to work, but we already have > 80 other dependencies in our API that are not having any issues importing. (It's an express API)

Thanks in advance for any help, I'm quite excited to give this library a try!

### Steps to reproduce

1. Import and use the library
```typescript
import ModernError from "modern-errors";

const BaseError = ModernError.subclass("BaseError");
throw new BaseError("test");
```
2. Start app with `ts-node-dev`
3. See following stack trace:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/jack/workspace/my-project/api/node_modules/modern-errors/build/src/main.js from /Users/jack/workspace/my-project/api/src/index.ts not supported.
Instead change the require of main.js in /Users/jack/workspace/my-project/api/src/index.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions..jsx.require.extensions..js (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:114:20)
    at Object.nodeDevHook [as .js] (/Users/jack/workspace/my-project/api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/jack/workspace/my-project/api/src/index.ts:68:41)
    at Module._compile (/Users/jack/workspace/my-project/api/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:69:33)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:114:20)
    at require.extensions.<computed> (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:71:20)
    at Object.nodeDevHook [as .ts] (/Users/jack/workspace/my-project/api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Object.<anonymous> (/Users/jack/workspace/my-project/api/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (/Users/jack/workspace/my-project/api/node_modules/source-map-support/source-map-support.js:547:25)
    at Object.require.extensions..jsx.require.extensions..js (/private/var/folders/8n/dqgv9b4j797cqd34zb62ythw0000gn/T/ts-node-dev-hook-0371657800851346.js:95:24)
```

### tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["es2021"],
    "target": "es2019",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "rootDir": "./",
    "outDir": ".build",
    "allowJs": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "typeRoots": ["node_modules/@types", "generated"],
  },
  "exclude": ["node_modules"]
}
```

### Environment

 ```
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 158.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.113
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.1
```

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by Jackman3005** [comment]
Apologies, I made this issue in the wrong repo! I've moved it to a [new issue](https://github.com/ehmicky/modern-errors/issues/3) in the main modern-errors library.
